# Generated by Django 5.2.5 on 2026-01-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0005_rename_contactmessage_contact_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact_message",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
    ]
