"""
Django settings for myweb project.

Generated by 'django-admin startproject' using Django 4.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from whitenoise import WhiteNoise

# import logging
# logging.basicConfig(level=logging.DEBUG)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_DIR=os.path.dirname(os.path.abspath(__file__))





# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-n9*oyzoy=atm7tkqxzs!qc0%gc+toj-!@6^4jk4liqn@=+hvla"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["pjtech.onrender.com", "localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "crispy_forms",
    "crispy_bootstrap5",
    "userapp",
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware", # <-- add this
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# STORAGES = {
#     "staticfiles": {
#         "default": {
#         "BACKEND": "django.core.files.storage.FileSystemStorage",
#     },
#         "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
#     },
# }

# STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
# # STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


ROOT_URLCONF = "myweb.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ['%s/templates/' % (PROJECT_DIR),],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",
            ],
        },
    },
]

WSGI_APPLICATION = "myweb.wsgi.application"
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'pelmijosh@gmail.com'
EMAIL_HOST_PASSWORD = 'ykdv rdpn jinl velv'  # Not your regular Gmail password!
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

CONTACT_EMAIL = 'pelmijosh@gmail.com'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

#Database
#https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "myweb",
        "USER": "root",
        "PASSWORD": "OldStunna27!",
        "HOST": "localhost",
        "PORT": "3306",
        "OPTIONS": {
            "autocommit": True,
        },

    }
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'myweb_ino8',  # Your database name on Render
#         'USER': 'myweb_ino8_user',
#         'PASSWORD': 'M5PRywVjjzaKRdDvyAjAJy8ZSqWp122x',
#         'HOST': 'dpg-d2hpgh24d50c73bmbr7g-a.oregon-postgres.render.com',
#         'PORT': '5432',
#         'OPTIONS': {
#             'sslmode': 'require',
#         },

#     }
# }

# DATABASES = {
#     "default": dj_database_url.config(
#         default="postgresql://myweb_ino8_user:M5PRywVjjzaKRdDvyAjAJy8ZSqWp122x@dpg-d2hpgh24d50c73bmbr7g-a.oregon-postgres.render.com:5432/myweb_ino8",
#         conn_max_age=600,
#     )
# }



# DATABASES = {
#     "default": dj_database_url.config(
#         default="postgresql://myweb_ino8_user:M5PRywVjjzaKRdDvyAjAJy8ZSqWp122x@dpg-d2hpgh24d50c73bmbr7g-a.oregon-postgres.render.com:5432/myweb_ino8",
#         conn_max_age=600,
#         ssl_require=True
#     )
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# STATICFILES_DIRS=[
#     os.path.join(BASE_DIR, "static")]

STATICFILES_DIRS = [BASE_DIR / "static"]

# This is where collectstatic will put all static files
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL="home"
LOGOUT_REDIRECT_URL="home"